name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    Artefact-creation:
        runs-on: ubuntu-latest

        steps:
            - name: Récupérer le code
              uses: actions/checkout@v5

            - name: Installer NodeJS
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: "npm"

            - name: Installer les dépendances
              run: npm ci

            - name: Build chrome
              run: npm run build

            - name: Build Firefox
              run: npm run build:firefox

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: chrome
                  path: |
                      .output
